import { type NextPage } from "next";
import Head from "next/head";
import { SignIn, UserButton, useUser } from "@clerk/nextjs";

import Link from "next/link";

const Home: NextPage = () => {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!user.isSignedIn ? (
        <SignIn />
      ) : (
        <div>
          <nav className="flex justify-end">
            <div className="self-start">Song2Image</div>
            <Link href="/imagine">Create new</Link>
            <UserButton />
          </nav>
          <main>
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              Convert a song into an{" "}
              <span className="text-[hsl(280,100%,70%)]">image</span>!
            </h1>
            <div className="grid grid-cols-4 grid-rows-4 gap-5">
              {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11].map((item) => (
                <button key={item}>Image</button>
              ))}
            </div>
          </main>
        </div>
      )}
    </>
  );
};

export default Home;
