import { type NextPage } from "next";
import Head from "next/head";
import { SignIn, UserButton, useUser } from "@clerk/nextjs";

import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { user, isSignedIn } = useUser();

  const { data: isNewUser } = api.user.createUser.useQuery();
  const { data: postsData } = api.post.getAllPosts.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isNewUser ? <div>Welcome {user?.fullName}</div> : null}
      {!isSignedIn ? (
        <div className="flex h-screen w-screen items-center justify-center">
          <SignIn />
        </div>
      ) : (
        <div className="grid grid-cols-8">
          <nav className="col-start-1 col-end-9 flex w-full items-center justify-end gap-5 bg-purple-900 p-7">
            <h1 className="mr-auto cursor-pointer text-2xl font-extrabold text-white">
              🪩Song2Image
            </h1>
            <Link
              href="/imagine"
              className="rounded-3xl bg-green-500 px-3 py-2 font-semibold text-white"
            >
              Create new
            </Link>
            <UserButton />
          </nav>
          <main className="col-start-2 col-end-8">
            <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]">
              Convert a song into an image!
            </h1>
            <div className="grid grid-cols-4 grid-rows-4 gap-5">
              {postsData?.posts.map((post) => (
                <button key={post.id} className="h-40 w-40 border border-black">
                  {post.prompt}
                </button>
              ))}
            </div>
          </main>
        </div>
      )}
    </>
  );
};

export default Home;
