import Image from "next/image";
import Link from "next/link";
import React from "react";
import { api } from "~/utils/api";

type Props = {
  postId: string;
  open: boolean;
  onClose: () => void;
};

export default function Post({ postId, open, onClose }: Props) {
  const audioRef = React.useRef<HTMLAudioElement | null>(null);

  const { data, isLoading } = api.post.getPostById.useQuery({ postId });

  React.useEffect(() => {
    () => {
      if (audioRef.current) {
        audioRef.current.pause();
        audioRef.current.currentTime = 0;
      }
    };
  }, []);

  if (isLoading) return null;

  return (
    <dialog
      open={open}
      className="absolute flex w-full justify-around border border-black"
    >
      <Image
        src={data?.postInfo?.image as string}
        alt="art generated"
        height={500}
        width={500}
      />
      <div className="flex flex-col gap-3">
        <div className="flex justify-between">
          <h3 className="text-4xl font-bold">
            {data?.postInfo?.song.songName}
          </h3>
          <button
            className="border border-black bg-slate-200 p-1"
            onClick={onClose}
          >
            Close
          </button>
        </div>
        <p>Generated by {data?.postInfo?.User.username}</p>
        <div>
          <b>Prompt:</b>
          <p>{data?.postInfo?.prompt}</p>
        </div>
        <Link
          className="mt-auto rounded-3xl bg-green-500 px-3 py-2 text-center font-semibold text-white"
          href={data?.postInfo?.song.songUri as string}
        >
          Open on Spotify
        </Link>
      </div>
      <audio ref={audioRef} className="hidden" autoPlay muted>
        <source src={data?.postInfo?.song.previewUrl} />
        Your browser does not support the audio element.
      </audio>
    </dialog>
  );
}
